---
# Commande de lancement du playbook
# ansible-playbook deploy_ct.yml --vault-password-file global_vars/pass --become-pass-file global_vars/become_pass
- hosts: localhost
  gather_facts: false
  vars_files:
    - global_vars/common.yml
  
  tasks:
    - name: Start roles with loop
      include_role:
        name: '{{ role.role }}'
      loop_control:
        loop_var: role
      loop:
        - { role: create_ct, tags: create_ct }
        - { role: add_host_ct, tags: add_host_ct }        
        - { role: proxmox_init_ct, tags: proxmox_init_ct }

- hosts: lxc 
  gather_facts: false
  vars_files:
   - global_vars/common.yml

  tasks:
    - name: Start roles with loop
      include_role:
        name: '{{ role.role }}'
      loop_control:
        loop_var: role
      loop:
        - { role: setup_ct, tags: setup_ct }
