---
- hosts: localhost
  gather_facts: false
  vars_files:
    - global_vars/common.yml
  
  tasks:
    - name: Start roles with loop
      include_role:
        name: '{{ role.role }}'
      loop_control:
        loop_var: role
      loop:
        - { role: get_downloadable_templates, tags: get_downloadable_templates }
