---
# Ajout du host dans /etc/hosts
- name: Set host in /etc/hosts
  ansible.builtin.lineinfile:
    path: /etc/hosts
    regexp: '^{{ base_ip }}'
    line: '{{ base_ip }} {{ VM_hostname }} {{ VM_hostname }}.{{ domain }}'
  become: true
