---
# tasks file for roles/ct_templating
- name: Stop LXC Container
  community.proxmox.proxmox: 
    node: '{{ proxmox_node }}'
    api_host: '{{ proxmox_host }}'
    api_port: '{{ proxmox_port }}'
    api_user: '{{ proxmox_user }}'
    api_token_id: '{{ proxmox_token_id }}'
    api_token_secret: '{{ proxmox_token_secret }}'
    vmid: '{{ base_vmid }}'
    state: 'stopped'

- name: Convert LXC to template
  community.proxmox.proxmox:
    node: '{{ proxmox_node }}'
    api_host: '{{ proxmox_host }}'
    api_port: '{{ proxmox_port }}'
    api_user: '{{ proxmox_user }}'
    api_token_id: '{{ proxmox_token_id }}'
    api_token_secret: '{{ proxmox_token_secret }}'
    vmid: '{{ base_vmid }}'
    state: 'template'