---
# tasks file for roles/basevmid_template
- name: Get Guests Proxmox List
  community.proxmox.proxmox_vm_info:
    node: '{{ proxmox_node }}'
    api_host: '{{ proxmox_host }}'
    api_port: '{{ proxmox_port }}'
    api_user: '{{ proxmox_user }}'
    api_token_id: '{{ proxmox_token_id }}'
    api_token_secret: '{{ proxmox_token_secret }}'
  register: proxmox_guests

- name: Set fact step_vmid
  set_fact:
    step_vmid: "{{ proxmox_guests.proxmox_vms | map(attribute='vmid') | max | int + 1 }}"
  when: proxmox_guests.proxmox_vms | map(attribute='vmid') | max | int + 1 > 999000

- name: Set fact New VMID
  set_fact:
    base_vmid: "{{ step_vmid | default(999000) }}"