---
# tasks file for setup-deploy
- name: Installing Base Packages
  package:
   name: '{{ base_packages }}'
   state: latest
  delegate_to: "{{ base_ip }}"

- name: Create sshusers Group
  group:
   name: sshusers
  delegate_to: "{{ base_ip }}"
 
- name: Create desigual User
  user:
   name: '{{ base_user }}'
   password: '{{ base_pass }}'
   shell: '{{ base_shell }}'
   groups: 
    - 'wheel'
    - 'sshusers'
  delegate_to: "{{ base_ip }}"

- name: Copy SSH Key to desigual User
  ansible.posix.authorized_key:
   user: '{{ base_user }}'
   state: present
   key: "{{ lookup('file','/root/.ssh/id_ed25519.pub') }}"
  delegate_to: "{{ base_ip }}"

- name: Copy SSH Configuration File
  copy:
   src: hardening.conf
   dest: /etc/ssh/sshd_config.d/
   owner: root
   group: root
   mode: 0644
  delegate_to: "{{ base_ip }}"
